# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sangaku-eyeball"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Hutchens"]
  s.date = "2013-03-15"
  s.description = "Sangaku Eyeball uses Gosu, a 2D Game Library, to display lines, polygons and so on as defined by the Sangaku gem. It allows you to draw arbitrary polygons and then locate the Pole of Inaccessibility (usually the best place to display a label) using a fast, iterative algorithm."
  s.email = "jason.hutchens@agworld.com.au"
  s.executables = ["sangaku-eyeball"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/sangaku-eyeball",
    "lib/sangaku-eyeball.rb",
    "lib/sangaku-eyeball/assets/cursor.png",
    "lib/sangaku-eyeball/assets/target.png",
    "lib/sangaku-eyeball/drawable.rb",
    "sangaku-eyeball.gemspec",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/agworld/sangaku-eyeball"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Sangaku Eyeball is a simple tool for visualising what the Sangaku gem can do."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gosu>, [">= 0"])
      s.add_runtime_dependency(%q<sangaku>, [">= 0.5.4"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
    else
      s.add_dependency(%q<gosu>, [">= 0"])
      s.add_dependency(%q<sangaku>, [">= 0.5.4"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
    end
  else
    s.add_dependency(%q<gosu>, [">= 0"])
    s.add_dependency(%q<sangaku>, [">= 0.5.4"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
  end
end

